import { ITransaction } from './transactions.types';

export const MOCK_TRANSACTIONS: ITransaction[] = [
  {
    id: 'tx-001',
    date: '2026-05-27',
    merchantName: 'QuickBooks Online',
    merchantInitials: 'QBO',
    merchantColor: '#4A90D9',
    accountMask: 'Chase ···· 4821',
    categoryName: 'Software & subscriptions',
    categoryColor: '#7C3AED',
    categorizationState: 'categorized',
    statuses: ['reconciled'],
    amount: -35.00,
    isIncome: false,
  },
  {
    id: 'tx-002',
    date: '2026-05-27',
    merchantName: 'Amazon Business',
    merchantInitials: 'AM',
    merchantColor: '#E54604',
    accountMask: 'Chase ···· 4821',
    categoryName: 'Office supplies',
    categoryColor: '#0780A6',
    categorizationState: 'categorized',
    statuses: [],
    amount: -142.87,
    isIncome: false,
  },
  {
    id: 'tx-003',
    date: '2026-05-26',
    merchantName: 'Google Ads',
    merchantInitials: 'GA',
    merchantColor: '#148672',
    accountMask: 'BOA ···· 2203',
    categoryName: 'Uncategorized',
    categoryColor: '#F15F22',
    categorizationState: 'needs_review',
    statuses: [],
    amount: -380.00,
    isIncome: false,
  },
  {
    id: 'tx-004',
    date: '2026-05-26',
    merchantName: 'Zoom',
    merchantInitials: 'ZM',
    merchantColor: '#3F5261',
    accountMask: 'Chase ···· 4821',
    categoryName: 'Software & subscriptions',
    categoryColor: '#7C3AED',
    categorizationState: 'categorized',
    statuses: ['reconciled'],
    amount: -16.99,
    isIncome: false,
  },
  {
    id: 'tx-005',
    date: '2026-05-25',
    merchantName: 'Client payment — Acme Corp',
    merchantInitials: 'CL',
    merchantColor: '#1776B6',
    accountMask: 'Chase ···· 4821',
    categoryName: 'Business income',
    categoryColor: '#148672',
    categorizationState: 'categorized',
    statuses: ['reconciled'],
    amount: 4500.00,
    isIncome: true,
  },
  {
    id: 'tx-006',
    date: '2026-05-25',
    merchantName: "Morton's The Steakhouse",
    merchantInitials: 'MR',
    merchantColor: '#C71D1D',
    accountMask: 'Amex ···· 9001',
    categoryName: 'Meals & entertainment',
    categoryColor: '#F34B04',
    categorizationState: 'categorized',
    statuses: [],
    amount: -213.40,
    isIncome: false,
  },
  {
    id: 'tx-007',
    date: '2026-05-24',
    merchantName: 'Slack Technologies',
    merchantInitials: 'SL',
    merchantColor: '#274F54',
    accountMask: 'Chase ···· 4821',
    categoryName: 'Uncategorized',
    categoryColor: '#F15F22',
    categorizationState: 'needs_review',
    statuses: [],
    amount: -87.50,
    isIncome: false,
  },
  {
    id: 'tx-008',
    date: '2026-05-23',
    merchantName: 'USPS Priority Shipping',
    merchantInitials: 'US',
    merchantColor: '#58595C',
    accountMask: 'Chase ···· 4821',
    categoryName: 'Shipping & postage',
    categoryColor: '#0780A6',
    categorizationState: 'categorized',
    statuses: ['reconciled'],
    amount: -28.75,
    isIncome: false,
  },
  {
    id: 'tx-009',
    date: '2026-05-22',
    merchantName: 'ComEd — Electric',
    merchantInitials: 'CW',
    merchantColor: '#1F7262',
    accountMask: 'BOA ···· 2203',
    categoryName: 'Utilities',
    categoryColor: '#3B7A80',
    categorizationState: 'categorized',
    statuses: ['reconciled'],
    amount: -194.22,
    isIncome: false,
  },
  {
    id: 'tx-010',
    date: '2026-05-21',
    merchantName: 'LinkedIn Premium',
    merchantInitials: 'LK',
    merchantColor: '#154C79',
    accountMask: 'Chase ···· 4821',
    categoryName: 'Software & subscriptions',
    categoryColor: '#7C3AED',
    categorizationState: 'categorized',
    statuses: ['transfer'],
    amount: -39.99,
    isIncome: false,
  },
  {
    id: 'tx-011',
    date: '2026-04-30',
    merchantName: 'Stripe — Payment processing',
    merchantInitials: 'SP',
    merchantColor: '#3F5261',
    accountMask: 'Chase ···· 4821',
    categoryName: 'Professional services',
    categoryColor: '#0780A6',
    categorizationState: 'categorized',
    statuses: ['reconciled'],
    amount: -56.42,
    isIncome: false,
  },
  {
    id: 'tx-012',
    date: '2026-04-29',
    merchantName: 'Office Depot',
    merchantInitials: 'OD',
    merchantColor: '#784E03',
    accountMask: 'Amex ···· 9001',
    categoryName: 'Uncategorized',
    categoryColor: '#F15F22',
    categorizationState: 'needs_review',
    statuses: ['duplicate'],
    amount: -74.19,
    isIncome: false,
  },
];
